export { default as Template1 } from './Template.vue'
export { default as ContentContact } from './Contact.vue'
export { default as ContentHeadingText } from './HeadingText.vue'
export { default as ContentImageText } from './ImageText.vue'
export { default as ContentProfile } from './Profile.vue'
export { default as ContentSocialLink } from './SocialLink.vue'