// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eubsempvsknwnulwzxfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1YnNlbXB2c2tud251bHd6eGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjU3MDMsImV4cCI6MjA2MjU0MTcwM30.0td2fHnSdfO9-a_n-hMf-5JfvNSHzGDmxWEX6eRdr_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);